### ISSUE TITLE
求更新Minecraft1.20版本

### ISSUE THREAD

**Issue by AkarinLiu** [CFPAOrg/I18nUpdateMod3#12]
现阶段，Minecraft1.20版本已正式发布，望作者能够跟上。

**Comment by JingHai-Lingyun** [comment]
同求

**Comment by AkarinLiu** [comment]
@Snownee @ustc-zzzz 麻烦跟上，否则会考虑移植到1.20版本，并发起Pull Request。

**Comment by xfl03** [comment]
已更新1.20和1.20.1版本
https://modrinth.com/mod/i18nupdatemod/version/TUfPUnrb
