### ISSUE TITLE
[1.7]在安装了汉化材质后高清修复中部分词条出现翻译错误

### ISSUE THREAD

**Issue by xx146542xx** [CFPAOrg/I18nUpdateMod3#17]
未安装和安装后 汉化包更新日期 12月11日 有mod自动下载
![image](https://github.com/CFPAOrg/I18nUpdateMod3/assets/109429390/5a19d6d7-71a9-43bb-ba21-aa8f547d28fc)
![image](https://github.com/CFPAOrg/I18nUpdateMod3/assets/109429390/e556b294-9daf-4b7a-b3b5-9a03b25c2032)

**Comment by xfl03** [comment]
有词条污染，请去简体中文资源包反馈
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues
