### ISSUE TITLE
自动加载资源包

### ISSUE THREAD

**Issue by TexBlock** [CFPAOrg/I18nUpdateMod3#3]
目前可以找到的通用资源包加载方案是https://github.com/CFPAOrg/I18nUpdateMod2/blob/1.16.5-fabric/src/main/java/com/github/tartaricacid/i18nupdatemod/OptionsUtils.java

这种直接改option文件的应该可以所有版本通用

**Comment by xfl03** [comment]
#2 
感谢方案
