### ISSUE TITLE
TranslationPackConvert 仓库即将添加新的转换

### ISSUE THREAD

**Issue by zkitefly** [CFPAOrg/I18nUpdateMod3#4]
![image](https://user-images.githubusercontent.com/64117916/212486253-e2afa668-93ba-4aa0-be16-93daf027faa5.png)
1.12.2 -> 1.9/1.10 1.6/1.7/1.8  

1.16 -> 1.13/1.14

征集下意见

**Comment by zkitefly** [comment]
https://github.com/zkitefly/TranslationPackConvert/pull/4

**Comment by zkitefly** [comment]
好吧，没人有啥意见我就合并了

**Comment by zkitefly** [comment]
> 

Merged!

**Comment by zkitefly** [comment]
@xfl03 记得添加相应支持哦

**Comment by xfl03** [comment]
目前Mod可以在1.11.2-1.19.3兼容，1.6-1.11.1还在努力兼容中
