### ISSUE TITLE
允许额外配置 Crowdin / Weblate / Pootle 更新源

### ISSUE THREAD

**Issue by pkstDev** [CFPAOrg/I18nUpdateMod3#5]
部分 Mod 的本地化是自成体系的（如 unascribed 就把本地化放在自搭的 Sleeping Town Weblate 上），如果可以额外配置从这些源拉取本地化会更好。
（我并没有说“汉化”，因为不能保证第三方源有简体中文翻译，而且如果有这样的功能的话玩家应该有权利选择想要的语言）

**Comment by xfl03** [comment]
这个我建议直接拉进资源包本身，别在Mod这边做工作
