### ISSUE TITLE
1.10使用特定的资源包

### ISSUE THREAD

**Issue by zkitefly** [CFPAOrg/I18nUpdateMod3#7]
该资源包来自 https://www.curseforge.com/minecraft/texture-packs/simplified-chinese-localization-resource-package ，选用最后一次更新的版本。原文件名为 `Minecraft-Mod-Language-Package-1.4.4`

因为停止更新，所以下载源不做自动更新。

文件地址：`https://gitcode.net/chearlai/translationpackconvert/-/raw/main/1-10/Minecraft-Mod-Language-Package-1-10.zip`
MD5：`https://gitcode.net/chearlai/translationpackconvert/-/raw/main/1-10/1-10.md5`

**Comment by zkitefly** [comment]
注意：改了下md5的名字
~`https://gitcode.net/chearlai/translationpackconvert/-/raw/main/1-10/1-10.md5`~
`https://gitcode.net/chearlai/translationpackconvert/-/raw/main/1-10/1.10.md5`

**Comment by xfl03** [comment]
加上啦
