### ISSUE TITLE
1.12整合包报下载失败，装了3.4也失败

### ISSUE THREAD

**Issue by vitechliu** [CFPAOrg/I18nUpdateMod3#9]
以前玩的艾维空岛1.12的整合包，印象中也是用这个汉化，效果还不错
过了几年重新玩，一样的版本，发现有很多翻译缺失，mc刚启动和进入世界时都会说版本太旧什么的，
我发现整合包里面用的是i18nupdatemod-1.12.2-1.0.8.jar，我删掉并换成了I18nUpdateMod-3.4.2-all.jar，然后发现没用，3.4版本启动后还是会在mod文件夹下载前者，并且随后会自动装载一个资源包，这个资源包显然有点过时，我随后手动下载了https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2444
这里的资源包，效果好了不少。

有几个问题就是，为什么老版本的i18n，mc刚启动和进入世界时都会报下载失败，但是仍然会加载一个资源包。同时按照指示装了最新版3.4的并不能解决这个问题

**Comment by xfl03** [comment]
> 4月5日前后就发现了这个问题，但是开发者一直没回复。需要暴力ping一下@xfl03 贴一下我的logs：
> 
> ```
> [2023-04-07 15:11:16] [INFO]: I18nUpdate Mod 3.4.2 is loaded in 1.12.2 with Forge
> [2023-04-07 15:11:16] [DEBUG]: Minecraft path: C:\Users\bing1\AppData\Roaming\.minecraft\versions\SimplePack
> [2023-04-07 15:11:16] [DEBUG]: User home: C:\Users\bing1
> [2023-04-07 15:11:16] [DEBUG]: Temp and current file has already been synchronized
> [2023-04-07 15:11:16] [DEBUG]: C:\Users\bing1\.i18nupdatemod\1.12.2\Minecraft-Mod-Language-Modpack.zip md5: bdfeb7afbe307b2c10448c2639b2067a, remote md5: BDFEB7AFBE307B2C10448C2639B2067A
> [2023-04-07 15:11:16] [DEBUG]: Already up to date.
> ```
> 
> 会加载资源包可能是因为本地有资源包缓存，我在删除了本地缓存后就不会自动加载资源包了

这不是从本地缓存里面加载了吗，你应该放一下删了本地缓存之后的日志

**Comment by luoxueyasha** [comment]
> 你应该放一下删了本地缓存之后的日志

现在好了（貌似是那两周下载源的问题
总之应该可以solved了
